apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: demotls
  namespace: kafka
  labels:
    app: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    replicas: 3
    version: 2.8.0
    config:
      # Replication factor for internal metadata topics. Production min 3
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: '2.8'
      inter.broker.protocol.version: '2.8'
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: routetls
        port: 9094
        type: route
        tls: true
        authentication:
          type: tls
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml 
    authorization:
      type: simple
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    storage:
      type: ephemeral
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  cruiseControl:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: cruise-control-metrics
          key: metrics-config.yml
