apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: books
  labels:
    strimzi.io/cluster: demotls
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 1
