apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: books
  labels:
    strimzi.io/cluster: demotls
  namespace: kafka
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3