apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: simple-kafka-producer
    app.kubernetes.io/component: simple-kafka-producer
    app.kubernetes.io/instance: simple-kafka-producer
  name: simple-kafka-producer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: simple-kafka-producer
status:
  loadBalancer: {}