apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}-{{ .Values.user.name }}
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1073741824
  partitions: {{ .Values.topic.partitions }}
  replicas: {{ .Values.topic.replicas }}
