apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-kafka-consumer
    app.kubernetes.io/component: simple-kafka-consumer
    app.kubernetes.io/instance: simple-kafka-consumer
  name: simple-kafka-consumer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: simple-kafka-consumer
status:
  loadBalancer: {}