apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 1
  serviceAccountName: prometheus-server
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false