apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
  namespace: openshift-operators
spec:
  config:
    # 60m * 60s * 1000ms = 1h
    retention.ms: 3600000
    # 1gb
    segment.bytes: 1073741824
  partitions: 1
  replicas: 2